### PR TITLE
Fix and Refactor Inject Route

### LINKED ISSUE #973: Orphaned tunnel interfaces in multi-subnet setup
**What happened?**
We observed traffic being lost between pods on certain nodes in our cluster and certain target IPs (EC2, RDS) within the same VPC. Only pods on a certain set of nodes were affected, while pods on other nodes could reach the target IPs without issue. The lost traffic manifested itself as total packet loss.

Traffic emerging from the host VMs themselves was not affected, i.e. the issue only occurred in traffic from kubernetes pods.

The k8s nodes are spread over three subnets, which may also contain other VMs or RDS instances. The traffic loss occurred on some nodes from one of the three subnets, while the target VM was assigned an IP from one of the remaining two subnets.

There are no Security Group or iptables rules (that I know of) impeding traffic between the affected pods/VMs.

The unifying cause seems to be the existence of tunnel interfaces on the hosts. We had six pods each trying to access a TCP port on IP 10.190.49.147. Three of these pods had no trouble getting through, while three pods experienced total packet loss. On all nodes with pods experiencing packet loss, there was an IPIP interface `tun-1019049147`, tunneling to 10.190.49.147. Example:
```
19: tun-1019049147@ens5: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 8961 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 10.190.54.142 peer 10.190.49.147
    inet6 fe80::5efe:abe:368e/64 scope link 
       valid_lft forever preferred_lft forever
```
This kind of interface did _not_ exist on nodes with pods without packet loss. I am not an expert in IP routing, but it seems that the pod traffic got lost in these orphaned tunnel interfaces. `routel` on an affected host shows the following entry:
```
         target            gateway          source    proto    scope    dev tbl
         [...]
  10.190.49.147                                                 linktun-1019049147 77
```
while `ip route` shows no mention of the `tun-1019049147` or `linktun-...` devices or the IP 10.190.49.147.

The kube-router log seems to indicate that 10.190.49.147 had at one point in time been assigned to a k8s node, which has since gone down. This IP was subsequently assigned to a new VM (which became the TCP target of our pods). It seems to me that kube-router did not remove the tunnel interface when it detected that the k8s node 10.190.49.147 went down. This seems to have led to an orphaned tunnel interface (and hence broken routing), when the IP was assigned to a new VM. Grepping the corresponding kube-router log for the target IP (entire log since the initial node provisioning) shows only the following entries:
```
time="2020-08-12T08:30:49Z" level=warning msg="received notification" Code=6 Communicated-Reason= Data="[]" Key=10.190.49.147 Subcode=2 Topic=Peer
time="2020-08-12T08:30:49Z" level=info msg="Peer Down" Key=10.190.49.147 Reason="notification-received code 6(cease) subcode 2(administrative shutdown)" State=BGP_FSM_ESTABLISHED Topic=Peer
I0812 08:30:49.979695       1 network_routes_controller.go:472] Tunnel interface: tun-1019049147 for the node 10.190.49.147 already exists.
I0812 08:31:46.263744       1 bgp_peers.go:341] Received node 10.190.49.147 removed update from watch API, so remove node from peer
time="2020-08-12T08:31:46Z" level=warning msg="failed to unset md5: setsockopt: no such file or directory" Key=10.190.49.147 Topic=Peer
time="2020-08-12T08:31:46Z" level=info msg="Delete a peer configuration for:10.190.49.147" Topic=Peer
```
The newly provisioned VM was assigned the IP 10.190.49.147 on 2020-08-19, so well after the k8s node being unregistered.

Please let me know if I can provide any more relevant logs or information.

**What did you expect to happen?**
I expected the traffic to reach the target IP from any pod within the cluster.

I expected no tunnel interface to 10.190.49.147 to be present on any k8s host.

**How can we reproduce the behavior you experienced?**
Unfortunately, I do not know how to reproduce the behavior at this point.

**System Information:**
 - Kube-Router Version: 0.4.0
 - Kubernetes Version: 1.15.12
 - Cloud Type: AWS
 - Kubernetes Deployment Type: kops
 - Kube-Router Deployment Type: DaemonSet
 - Cluster Size: 40 nodes (master+worker)
 - k8s host OS: Debian 10
 - k8s host docker version: 18.06.3-ce, build d7080c1

**Further information:**
kube-router daemonset configuration: https://gist.github.com/recombinationgroup/b94394c7ce336efc4e8d49a02caaf947
kube-router-cfg config map: https://gist.github.com/recombinationgroup/6a7699304013fa2df634fae841cf72cc
Output of various routing/ip commands on one of the affected hosts: https://gist.github.com/recombinationgroup/1561b52ecdce5df3efd6099b93572aba
Entire log of kube-router on the same affected host: https://gist.github.com/recombinationgroup/2fda27badd1cc04a6136681fc9e3216d

### PR DESCRIPTION
**Pull request by aauren**
@murali-reddy / @mrueg - I was originally setting out to fix #973 but as I got into the code I realized that it desperately needed to be refactored. So I did the refactoring first, mostly extracting methods to make the logic flow a little easier to read. However, I also made it a bit more performant as well by processing withdrawals first.

This also contains a fix for #973 by checking at path withdrawal time whether the reason for the withdrawal is because the peer is unestablished. If the peer is no longer established, then it attempts to clean up the tunnels as well as the routes. I found in my testing that when the tunnel was deleted the system also seemed to automatically clean up the routes that were in table `77`.

@murali-reddy I only did a small amount of local testing as we don't frequently remove nodes from our clusters. I'd appreciate any additional testing that you might be able to do on this.

### CODE REVIEW

File: pkg/controllers/routing/network_routes_controller.go [hunk 1]
```diff
@@ -508,130 +506,174 @@ func (nrc *NetworkRoutingController) advertisePodRoute() error {
...
+		Address: peerIP,
+	}, peerFunc)
+	if err != nil {
+		return false, fmt.Errorf("unable to list peers to see if tunnel & routes need to be removed: %v", err)
+	}
+
+	return peerDisconnected, nil
+}
+
+// cleanupTunnels removes any traces of tunnels / routes that were setup by nrc.setupOverlayTunnel() and are no longer
```
Comment (mrueg) [inline pkg/controllers/routing/network_routes_controller.go:614]: this should be cleanupTunnel (singular), right?

Comment (aauren) [reply pkg/controllers/routing/network_routes_controller.go]: Sure enough. Fixed.

**Comment by murali-reddy** [comment]
> @murali-reddy I only did a small amount of local testing as we don't frequently remove nodes from our clusters. I'd appreciate any additional testing that you might be able to do on this.

Thanks for the PR. I will do the necessary testing.

**Comment by murali-reddy** [comment]
@aauren thanks for working much needed refactoring to the `injectRoute`. I tested below scenarios

- ensured appropriate routes are setup across the nodes in the same subnet when `--overlay-type=subnet` and no tunnels are created
- ensured appropriate routes are setup across the nodes in the same subnet when `--overlay-type=full` and routes are set up via tunneled interface
- ensured routes are setup with tunneled interfaces when nodes are across the subnets in both the cases `--overlay-type=subnet`  and `--overlay-type=full` 
- ensured routing entry in custom routing table 77 is deleted

functionality wise it is working as expected

**Review by murali-reddy — APPROVED** [review]
