### PR TITLE
fix #639

### LINKED ISSUE #639: Removing ExternalIP Fails to Withdraw Route
I am using externalIPs to advertise out anycast BGP routes from kube-router. Advertising works as you'd expect: I add an externalIP and it is advertised. Unfortunately when removing the externalIP, the route is never withdrawn from my peers. 

Running kube-router version v0.2.0-beta.7, built on 2018-06-08T09:34:34+0000, go1.8.7

### PR DESCRIPTION
**Pull request by mk01**
- get external IPs to withdraw as diff against previous generation of service

### CODE REVIEW

File: pkg/controllers/routing/ecmp_vip.go [hunk 1]
```diff
@@ -65,7 +66,7 @@ func (nrc *NetworkRoutingController) newServiceEventHandler() cache.ResourceEven
 			nrc.OnServiceUpdate(obj)
 		},
 		UpdateFunc: func(oldObj, newObj interface{}) {
-			nrc.OnServiceUpdate(newObj)
+			nrc.OnServiceUpdate(newObj, oldObj)
```
Comment (murali-reddy) [inline pkg/controllers/routing/ecmp_vip.go]: @mk01 Please add new function `OnServiceCreate` and use it to handle `AddFunc`. And modify the signature of `OnServiceUpdate` to take the new and old objects explicitly (instead of objOld ...interface{})

There should have been separate handler for just Add to begin with. Nevertheless its good to modify it now.

**Comment by murali-reddy** [comment]
LGTM.
